---
abstract: 'Perl SDK for OpenTok'
author:
  - 'Maxim Nikolenko <root@zbsd.ru>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.112621'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OpenTok-API
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC_SHA1: 0
  Exception::Class: 0
  LWP: 0
  MIME::Base64: 0
  Test::More: 0
  Time::HiRes: 0
  XML::XPath: 0
version: 0.03
